[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo =  'scrooloose/syntastic'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'lvht/phpcd.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
